/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fsc_mpc_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[6] = {4, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s2[7] = {4, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};

/* fsc_mpc_expl_ode_fun:(i0[10],i1[4],i2)->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+14, w2, w3, *w4=w+19, w5, w6, *w7=w+25, *w8=w+27, *w9=w+30, *w10=w+34, *w11=w+37, w12, w13, w14;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 10, w0);
  /* #1: @1 = @0[7:10] */
  for (rr=w1, ss=w0+7; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @2 = zeros(4x1,1nz) */
  w2 = 0.;
  /* #4: @3 = @0[6] */
  for (rr=(&w3), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #5: @4 = input[1][0] */
  casadi_copy(arg[1], 4, w4);
  /* #6: @1 = @4[1:4] */
  for (rr=w1, ss=w4+1; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #7: @5 = 2 */
  w5 = 2.;
  /* #8: @1 = (@1/@5) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w5;
  /* #9: @5 = @1[0] */
  for (rr=(&w5), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (@3*@5) */
  w3 *= w5;
  /* #11: @5 = @0[4] */
  for (rr=(&w5), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #12: @6 = @1[2] */
  for (rr=(&w6), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #13: @5 = (@5*@6) */
  w5 *= w6;
  /* #14: @3 = (@3+@5) */
  w3 += w5;
  /* #15: @5 = @0[5] */
  for (rr=(&w5), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #16: @6 = @1[1] */
  for (rr=(&w6), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #17: @5 = (@5*@6) */
  w5 *= w6;
  /* #18: @3 = (@3-@5) */
  w3 -= w5;
  /* #19: (@2[0] = @3) */
  for (rr=(&w2)+0, ss=(&w3); rr!=(&w2)+1; rr+=1) *rr = *ss++;
  /* #20: @7 = project(@2) */
  casadi_project((&w2), casadi_s1, w7, casadi_s0, w);
  /* #21: @2 = @0[6] */
  for (rr=(&w2), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #22: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #23: @2 = (@2*@3) */
  w2 *= w3;
  /* #24: @3 = @0[5] */
  for (rr=(&w3), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #25: @5 = @1[0] */
  for (rr=(&w5), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #26: @3 = (@3*@5) */
  w3 *= w5;
  /* #27: @2 = (@2+@3) */
  w2 += w3;
  /* #28: @3 = @0[3] */
  for (rr=(&w3), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #29: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #30: @3 = (@3*@5) */
  w3 *= w5;
  /* #31: @2 = (@2-@3) */
  w2 -= w3;
  /* #32: (@7[1] = @2) */
  for (rr=w7+1, ss=(&w2); rr!=w7+2; rr+=1) *rr = *ss++;
  /* #33: @8 = project(@7) */
  casadi_project(w7, casadi_s0, w8, casadi_s2, w);
  /* #34: @2 = @0[6] */
  for (rr=(&w2), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #35: @3 = @1[2] */
  for (rr=(&w3), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #36: @2 = (@2*@3) */
  w2 *= w3;
  /* #37: @3 = @0[3] */
  for (rr=(&w3), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #38: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #39: @3 = (@3*@5) */
  w3 *= w5;
  /* #40: @2 = (@2+@3) */
  w2 += w3;
  /* #41: @3 = @0[4] */
  for (rr=(&w3), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #42: @5 = @1[0] */
  for (rr=(&w5), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #43: @3 = (@3*@5) */
  w3 *= w5;
  /* #44: @2 = (@2-@3) */
  w2 -= w3;
  /* #45: (@8[2] = @2) */
  for (rr=w8+2, ss=(&w2); rr!=w8+3; rr+=1) *rr = *ss++;
  /* #46: @9 = dense(@8) */
  casadi_densify(w8, casadi_s2, w9, 0);
  /* #47: @2 = @0[3] */
  for (rr=(&w2), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #48: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #49: @2 = (@2*@3) */
  w2 *= w3;
  /* #50: @2 = (-@2) */
  w2 = (- w2 );
  /* #51: @3 = @0[4] */
  for (rr=(&w3), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #52: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #53: @3 = (@3*@5) */
  w3 *= w5;
  /* #54: @2 = (@2-@3) */
  w2 -= w3;
  /* #55: @3 = @0[5] */
  for (rr=(&w3), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #56: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #57: @3 = (@3*@5) */
  w3 *= w5;
  /* #58: @2 = (@2-@3) */
  w2 -= w3;
  /* #59: (@9[3] = @2) */
  for (rr=w9+3, ss=(&w2); rr!=w9+4; rr+=1) *rr = *ss++;
  /* #60: output[0][1] = @9 */
  if (res[0]) casadi_copy(w9, 4, res[0]+3);
  /* #61: @1 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w1);
  /* #62: @2 = 0 */
  w2 = 0.;
  /* #63: @3 = 0 */
  w3 = 0.;
  /* #64: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #65: @6 = input[2][0] */
  w6 = arg[2] ? arg[2][0] : 0;
  /* #66: @5 = (@5/@6) */
  w5 /= w6;
  /* #67: @8 = vertcat(@2, @3, @5) */
  rr=w8;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w5;
  /* #68: @2 = @0[6] */
  for (rr=(&w2), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #69: @3 = @0[4] */
  for (rr=(&w3), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #70: @3 = (@3*@5) */
  w3 *= w5;
  /* #71: @6 = @0[3] */
  for (rr=(&w6), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #72: @6 = (@6*@5) */
  w6 *= w5;
  /* #73: @6 = (-@6) */
  w6 = (- w6 );
  /* #74: @5 = 0 */
  w5 = 0.;
  /* #75: @10 = vertcat(@3, @6, @5) */
  rr=w10;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w5;
  /* #76: @10 = (2.*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #77: @11 = (@2*@10) */
  for (i=0, rr=w11, cs=w10; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #78: @8 = (@8+@11) */
  for (i=0, rr=w8, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #79: @2 = @0[4] */
  for (rr=(&w2), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #80: @3 = @10[2] */
  for (rr=(&w3), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #81: @6 = (@2*@3) */
  w6  = (w2*w3);
  /* #82: @5 = @0[5] */
  for (rr=(&w5), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #83: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #84: @13 = (@5*@12) */
  w13  = (w5*w12);
  /* #85: @6 = (@6-@13) */
  w6 -= w13;
  /* #86: @13 = @10[0] */
  for (rr=(&w13), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #87: @5 = (@5*@13) */
  w5 *= w13;
  /* #88: @14 = @0[3] */
  for (rr=(&w14), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #89: @3 = (@14*@3) */
  w3  = (w14*w3);
  /* #90: @5 = (@5-@3) */
  w5 -= w3;
  /* #91: @14 = (@14*@12) */
  w14 *= w12;
  /* #92: @2 = (@2*@13) */
  w2 *= w13;
  /* #93: @14 = (@14-@2) */
  w14 -= w2;
  /* #94: @10 = vertcat(@6, @5, @14) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w14;
  /* #95: @8 = (@8+@10) */
  for (i=0, rr=w8, cs=w10; i<3; ++i) (*rr++) += (*cs++);
  /* #96: @1 = (@1+@8) */
  for (i=0, rr=w1, cs=w8; i<3; ++i) (*rr++) += (*cs++);
  /* #97: output[0][2] = @1 */
  if (res[0]) casadi_copy(w1, 3, res[0]+7);
  return 0;
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fsc_mpc_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fsc_mpc_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fsc_mpc_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void fsc_mpc_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fsc_mpc_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int fsc_mpc_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fsc_mpc_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fsc_mpc_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fsc_mpc_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fsc_mpc_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fsc_mpc_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 43;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
