/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fsc_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sparsify CASADI_PREFIX(sparsify)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[7] = {4, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[6] = {4, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s3[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s6[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

/* fsc_mpc_expl_vde_adj:(i0[10],i1[10],i2[4],i3)->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+14, w2, *w3=w+25, w4, w5, w6, w7, w8, w9, *w10=w+35, *w11=w+38, *w12=w+48, *w13=w+51, *w14=w+55, w15, w16, w17, w18, *w19=w+62, *w20=w+65, *w21=w+68;
  /* #0: @0 = zeros(10x1) */
  casadi_clear(w0, 10);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 10, w1);
  /* #2: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #3: @3 = input[2][0] */
  casadi_copy(arg[2], 4, w3);
  /* #4: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @4 = (@4/@5) */
  w4 /= w5;
  /* #7: @6 = (@2*@4) */
  w6  = (w2*w4);
  /* #8: @7 = @1[3] */
  for (rr=(&w7), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #9: @8 = (@7*@4) */
  w8  = (w7*w4);
  /* #10: @8 = (-@8) */
  w8 = (- w8 );
  /* #11: @9 = 0 */
  w9 = 0.;
  /* #12: @10 = vertcat(@6, @8, @9) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w9;
  /* #13: @10 = (2.*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #14: @6 = @10[1] */
  for (rr=(&w6), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #15: @11 = input[1][0] */
  casadi_copy(arg[1], 10, w11);
  /* #16: {@12, @13, @14} = vertsplit(@11) */
  casadi_copy(w11, 3, w12);
  casadi_copy(w11+3, 4, w13);
  casadi_copy(w11+7, 3, w14);
  /* #17: {@8, @9, @15} = vertsplit(@14) */
  w8 = w14[0];
  w9 = w14[1];
  w15 = w14[2];
  /* #18: @16 = (@6*@15) */
  w16  = (w6*w15);
  /* #19: @17 = @10[2] */
  for (rr=(&w17), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #20: @18 = (@17*@9) */
  w18  = (w17*w9);
  /* #21: @16 = (@16-@18) */
  w16 -= w18;
  /* #22: (@0[3] += @16) */
  for (rr=w0+3, ss=(&w16); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #23: @16 = @10[0] */
  for (rr=(&w16), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #24: @18 = (@16*@9) */
  w18  = (w16*w9);
  /* #25: @6 = (@6*@8) */
  w6 *= w8;
  /* #26: @18 = (@18-@6) */
  w18 -= w6;
  /* #27: (@0[5] += @18) */
  for (rr=w0+5, ss=(&w18); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #28: @17 = (@17*@8) */
  w17 *= w8;
  /* #29: @16 = (@16*@15) */
  w16 *= w15;
  /* #30: @17 = (@17-@16) */
  w17 -= w16;
  /* #31: (@0[4] += @17) */
  for (rr=w0+4, ss=(&w17); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #32: @19 = zeros(3x1) */
  casadi_clear(w19, 3);
  /* #33: @17 = @1[5] */
  for (rr=(&w17), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #34: @16 = (@17*@9) */
  w16  = (w17*w9);
  /* #35: @18 = @1[4] */
  for (rr=(&w18), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #36: @6 = (@18*@15) */
  w6  = (w18*w15);
  /* #37: @16 = (@16-@6) */
  w16 -= w6;
  /* #38: (@19[0] += @16) */
  for (rr=w19+0, ss=(&w16); rr!=w19+1; rr+=1) *rr += *ss++;
  /* #39: @16 = @1[3] */
  for (rr=(&w16), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #40: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #41: @17 = (@17*@8) */
  w17 *= w8;
  /* #42: @15 = (@15-@17) */
  w15 -= w17;
  /* #43: (@19[1] += @15) */
  for (rr=w19+1, ss=(&w15); rr!=w19+2; rr+=1) *rr += *ss++;
  /* #44: @18 = (@18*@8) */
  w18 *= w8;
  /* #45: @16 = (@16*@9) */
  w16 *= w9;
  /* #46: @18 = (@18-@16) */
  w18 -= w16;
  /* #47: (@19[2] += @18) */
  for (rr=w19+2, ss=(&w18); rr!=w19+3; rr+=1) *rr += *ss++;
  /* #48: @18 = @1[6] */
  for (rr=(&w18), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #49: @20 = (@18*@14) */
  for (i=0, rr=w20, cs=w14; i<3; ++i) (*rr++)  = (w18*(*cs++));
  /* #50: @19 = (@19+@20) */
  for (i=0, rr=w19, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #51: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #52: {@18, @16, NULL} = vertsplit(@19) */
  w18 = w19[0];
  w16 = w19[1];
  /* #53: @9 = (@4*@16) */
  w9  = (w4*w16);
  /* #54: @9 = (-@9) */
  w9 = (- w9 );
  /* #55: (@0[3] += @9) */
  for (rr=w0+3, ss=(&w9); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #56: @4 = (@4*@18) */
  w4 *= w18;
  /* #57: (@0[4] += @4) */
  for (rr=w0+4, ss=(&w4); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #58: @4 = dot(@10, @14) */
  w4 = casadi_dot(3, w10, w14);
  /* #59: (@0[6] += @4) */
  for (rr=w0+6, ss=(&w4); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #60: @10 = @3[1:4] */
  for (rr=w10, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #61: @4 = 2 */
  w4 = 2.;
  /* #62: @10 = (@10/@4) */
  for (i=0, rr=w10; i<3; ++i) (*rr++) /= w4;
  /* #63: @4 = @10[2] */
  for (rr=(&w4), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #64: @9 = @13[3] */
  for (rr=(&w9), ss=w13+3; ss!=w13+4; ss+=1) *rr++ = *ss;
  /* #65: @4 = (@4*@9) */
  w4 *= w9;
  /* #66: @4 = (-@4) */
  w4 = (- w4 );
  /* #67: (@0[5] += @4) */
  for (rr=w0+5, ss=(&w4); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #68: @4 = @10[1] */
  for (rr=(&w4), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #69: @4 = (@4*@9) */
  w4 *= w9;
  /* #70: @4 = (-@4) */
  w4 = (- w4 );
  /* #71: (@0[4] += @4) */
  for (rr=w0+4, ss=(&w4); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #72: @4 = @10[0] */
  for (rr=(&w4), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #73: @4 = (@4*@9) */
  w4 *= w9;
  /* #74: @4 = (-@4) */
  w4 = (- w4 );
  /* #75: (@0[3] += @4) */
  for (rr=w0+3, ss=(&w4); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #76: @4 = @10[0] */
  for (rr=(&w4), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #77: @8 = 0 */
  w8 = 0.;
  /* #78: (@13[3] = @8) */
  for (rr=w13+3, ss=(&w8); rr!=w13+4; rr+=1) *rr = *ss++;
  /* #79: @19 = project(@13) */
  casadi_sparsify(w13, w19, casadi_s0, 0);
  /* #80: @8 = @19[2] */
  for (rr=(&w8), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #81: @4 = (@4*@8) */
  w4 *= w8;
  /* #82: @4 = (-@4) */
  w4 = (- w4 );
  /* #83: (@0[4] += @4) */
  for (rr=w0+4, ss=(&w4); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #84: @4 = @10[1] */
  for (rr=(&w4), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #85: @4 = (@4*@8) */
  w4 *= w8;
  /* #86: (@0[3] += @4) */
  for (rr=w0+3, ss=(&w4); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #87: @4 = @10[2] */
  for (rr=(&w4), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #88: @4 = (@4*@8) */
  w4 *= w8;
  /* #89: (@0[6] += @4) */
  for (rr=w0+6, ss=(&w4); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #90: @4 = @10[2] */
  for (rr=(&w4), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #91: @15 = 0 */
  w15 = 0.;
  /* #92: (@19[2] = @15) */
  for (rr=w19+2, ss=(&w15); rr!=w19+3; rr+=1) *rr = *ss++;
  /* #93: @21 = project(@19) */
  casadi_project(w19, casadi_s0, w21, casadi_s1, w);
  /* #94: @15 = @21[1] */
  for (rr=(&w15), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #95: @4 = (@4*@15) */
  w4 *= w15;
  /* #96: @4 = (-@4) */
  w4 = (- w4 );
  /* #97: (@0[3] += @4) */
  for (rr=w0+3, ss=(&w4); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #98: @4 = @10[0] */
  for (rr=(&w4), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #99: @4 = (@4*@15) */
  w4 *= w15;
  /* #100: (@0[5] += @4) */
  for (rr=w0+5, ss=(&w4); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #101: @4 = @10[1] */
  for (rr=(&w4), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #102: @4 = (@4*@15) */
  w4 *= w15;
  /* #103: (@0[6] += @4) */
  for (rr=w0+6, ss=(&w4); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #104: @4 = @10[1] */
  for (rr=(&w4), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #105: @17 = 0 */
  w17 = 0.;
  /* #106: (@21[1] = @17) */
  for (rr=w21+1, ss=(&w17); rr!=w21+2; rr+=1) *rr = *ss++;
  /* #107: @17 = project(@21) */
  casadi_project(w21, casadi_s1, (&w17), casadi_s2, w);
  /* #108: @6 = @17[0] */
  for (rr=(&w6), ss=(&w17)+0; ss!=(&w17)+1; ss+=1) *rr++ = *ss;
  /* #109: @4 = (@4*@6) */
  w4 *= w6;
  /* #110: @4 = (-@4) */
  w4 = (- w4 );
  /* #111: (@0[5] += @4) */
  for (rr=w0+5, ss=(&w4); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #112: @4 = @10[2] */
  for (rr=(&w4), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #113: @4 = (@4*@6) */
  w4 *= w6;
  /* #114: (@0[4] += @4) */
  for (rr=w0+4, ss=(&w4); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #115: @4 = @10[0] */
  for (rr=(&w4), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #116: @4 = (@4*@6) */
  w4 *= w6;
  /* #117: (@0[6] += @4) */
  for (rr=w0+6, ss=(&w4); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #118: (@0[7:10] += @12) */
  for (rr=w0+7, ss=w12; rr!=w0+10; rr+=1) *rr += *ss++;
  /* #119: output[0][0] = @0 */
  casadi_copy(w0, 10, res[0]);
  /* #120: @13 = zeros(4x1) */
  casadi_clear(w13, 4);
  /* #121: @2 = (@2*@18) */
  w2 *= w18;
  /* #122: @7 = (@7*@16) */
  w7 *= w16;
  /* #123: @2 = (@2-@7) */
  w2 -= w7;
  /* #124: {NULL, NULL, @7} = vertsplit(@14) */
  w7 = w14[2];
  /* #125: @2 = (@2+@7) */
  w2 += w7;
  /* #126: @2 = (@2/@5) */
  w2 /= w5;
  /* #127: (@13[0] += @2) */
  for (rr=w13+0, ss=(&w2); rr!=w13+1; rr+=1) *rr += *ss++;
  /* #128: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #129: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #130: @5 = @1[5] */
  for (rr=(&w5), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #131: @5 = (@5*@9) */
  w5 *= w9;
  /* #132: @5 = (-@5) */
  w5 = (- w5 );
  /* #133: (@14[2] += @5) */
  for (rr=w14+2, ss=(&w5); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #134: @5 = @1[4] */
  for (rr=(&w5), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #135: @5 = (@5*@9) */
  w5 *= w9;
  /* #136: @5 = (-@5) */
  w5 = (- w5 );
  /* #137: (@14[1] += @5) */
  for (rr=w14+1, ss=(&w5); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #138: @5 = @1[3] */
  for (rr=(&w5), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #139: @5 = (@5*@9) */
  w5 *= w9;
  /* #140: @5 = (-@5) */
  w5 = (- w5 );
  /* #141: (@14[0] += @5) */
  for (rr=w14+0, ss=(&w5); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #142: @5 = @1[4] */
  for (rr=(&w5), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #143: @5 = (@5*@8) */
  w5 *= w8;
  /* #144: @5 = (-@5) */
  w5 = (- w5 );
  /* #145: (@14[0] += @5) */
  for (rr=w14+0, ss=(&w5); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #146: @5 = @1[3] */
  for (rr=(&w5), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #147: @5 = (@5*@8) */
  w5 *= w8;
  /* #148: (@14[1] += @5) */
  for (rr=w14+1, ss=(&w5); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #149: @5 = @1[6] */
  for (rr=(&w5), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #150: @5 = (@5*@8) */
  w5 *= w8;
  /* #151: (@14[2] += @5) */
  for (rr=w14+2, ss=(&w5); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #152: @5 = @1[3] */
  for (rr=(&w5), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #153: @5 = (@5*@15) */
  w5 *= w15;
  /* #154: @5 = (-@5) */
  w5 = (- w5 );
  /* #155: (@14[2] += @5) */
  for (rr=w14+2, ss=(&w5); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #156: @5 = @1[5] */
  for (rr=(&w5), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #157: @5 = (@5*@15) */
  w5 *= w15;
  /* #158: (@14[0] += @5) */
  for (rr=w14+0, ss=(&w5); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #159: @5 = @1[6] */
  for (rr=(&w5), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #160: @5 = (@5*@15) */
  w5 *= w15;
  /* #161: (@14[1] += @5) */
  for (rr=w14+1, ss=(&w5); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #162: @5 = @1[5] */
  for (rr=(&w5), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #163: @5 = (@5*@6) */
  w5 *= w6;
  /* #164: @5 = (-@5) */
  w5 = (- w5 );
  /* #165: (@14[1] += @5) */
  for (rr=w14+1, ss=(&w5); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #166: @5 = @1[4] */
  for (rr=(&w5), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #167: @5 = (@5*@6) */
  w5 *= w6;
  /* #168: (@14[2] += @5) */
  for (rr=w14+2, ss=(&w5); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #169: @5 = @1[6] */
  for (rr=(&w5), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #170: @5 = (@5*@6) */
  w5 *= w6;
  /* #171: (@14[0] += @5) */
  for (rr=w14+0, ss=(&w5); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #172: @14 = (@2*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #173: (@13[1:4] += @14) */
  for (rr=w13+1, ss=w14; rr!=w13+4; rr+=1) *rr += *ss++;
  /* #174: output[0][1] = @13 */
  if (res[0]) casadi_copy(w13, 4, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fsc_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fsc_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fsc_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void fsc_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fsc_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int fsc_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fsc_mpc_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fsc_mpc_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fsc_mpc_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fsc_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fsc_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fsc_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 70;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
