[project]
authors = [{ name = "H S Helson Go", email = "hei.go@mail.utoronto.ca" }]
name = "quadrotor_mpc"
version = "0.0.1"
description = "Quadrotor control with acados"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = ["numpy", "acados_template", "casadi", "scipy"]

[project.optional-dependencies]
dev = ["matplotlib"]

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning"
pythonpath = ["./src"]

[tool.isort]
profile = "black"
